import {requireUser} from '../auth/session';
import {query,ownerId} from '../server/db';
import {getProfile,getFacts} from './business';
import {effectiveConfidence} from '../memory/store';
import {isFresh} from '../memory/working';
export async function listChunks(params:{q?:string;act?:string;type?:string;status?:string;page?:string}={}){await requireUser();const values=[(params.q||'').slice(0,200),(params.act||'').slice(0,80),(params.type||'').slice(0,40),(params.status||'').slice(0,40)];const where="where ($1='' or id ilike '%'||$1||'%' or text ilike '%'||$1||'%') and ($2='' or act=$2) and ($3='' or provision_type=$3) and ($4='' or status=$4)";const chunks=(await query(`select id,act,doc_type,provision_type,section,heading_path,effective_date,status,source_doc_id,text,coverage from gstpilot_legal_chunks ${where} order by id limit 100`,values)).rows;const count=Number((await query(`select count(*) n from gstpilot_legal_chunks ${where}`,values)).rows[0].n);return {chunks,count};}
export async function getChunk(id:string){await requireUser();return (await query('select * from gstpilot_legal_chunks where id=$1',[id.slice(0,200)])).rows[0]||null;}
export async function listTraces(){const u=await requireUser();return (await query('select * from gstpilot_retrieval_traces where owner_id=$1 order by created_at desc limit 100',[u.id])).rows;}
export async function getTrace(id:string){const u=await requireUser();return (await query('select * from gstpilot_retrieval_traces where id=$1 and owner_id=$2',[ownerId(id),u.id])).rows[0]||null;}
export async function listEvalRuns(){const u=await requireUser();return (await query('select * from gstpilot_eval_runs where owner_id=$1 order by created_at desc limit 50',[u.id])).rows;}
export async function getEvalRun(id:string){const u=await requireUser();return (await query('select * from gstpilot_eval_runs where id=$1 and owner_id=$2',[ownerId(id),u.id])).rows[0]||null;}
export async function listConversations(){const u=await requireUser();return (await query('select * from gstpilot_messages where owner_id=$1 order by created_at desc limit 80',[u.id])).rows;}
export async function loadMemoryInAction(){const u=await requireUser();const profile=await getProfile(u.id);const facts=await getFacts(u.id);const threads=(await query('select id,title,pending,created_at from gstpilot_threads where user_id=$1 and pending is not null order by created_at desc limit 10',[u.id])).rows;return {users:profile?[{...profile,facts:facts.map(f=>({...f,effective:Number(effectiveConfidence(f).toFixed(2)),as_of:new Date(f.as_of).toISOString().slice(0,10),last_confirmed:f.last_confirmed?new Date(f.last_confirmed).toISOString().slice(0,10):null})),pendings:threads.map(t=>({thread_id:t.id,title:t.title,fresh:isFresh(t.pending),pending:t.pending}))}]:[]};}
