import test from 'node:test';
import assert from 'node:assert/strict';
import {Identity, StaleResponse, readProtected, protectedHeaders} from '../lib/client/identity';
function stream() { let controller!: ReadableStreamDefaultController<Uint8Array>; let cancelled = false; const response = new Response(new ReadableStream<Uint8Array>({start(c){controller=c;},cancel(){cancelled=true;}})); return {response,send:(s:string)=>controller.enqueue(new TextEncoder().encode(s)),close:()=>controller.close(),cancelled:()=>cancelled}; }
const frame = (v:unknown) => `data: ${JSON.stringify(v)}\n\n`;
test('cross-tab invalidation aborts owned requests before the replacement session arrives', () => { const id=new Identity(); id.accept('A'); const a=id.capture(), controller=new AbortController();id.controllers.add(controller);id.accept(null,true);assert.equal(id.current(a),false);assert.equal(controller.signal.aborted,true);id.accept('B');assert.equal(id.current(a),false); });
test('GET carries expected owner; changed-cookie mismatch expires the still-current A view', async()=>{const id=new Identity();id.accept('A');const a=id.capture();assert.deepEqual(protectedHeaders(a.owner!,'csrf','GET'),{'X-GSTPilot-Owner':'A'});let expired=0;await assert.rejects(readProtected(new Response(JSON.stringify({error:'session_expired'}),{status:409}),()=>id.current(a),()=>{expired++;id.accept(null,true);}),StaleResponse);assert.equal(expired,1);assert.equal(id.owner,null);});
test('late A JSON cannot install after B signs in during body parsing',async()=>{const id=new Identity();id.accept('A');const a=id.capture(),s=stream();const pending=readProtected(s.response,()=>id.current(a),()=>assert.fail('must not expire B'));s.send('{"private":');await Promise.resolve();id.accept('B');s.send('"A"}');s.close();await assert.rejects(pending,StaleResponse);assert.equal(id.owner,'B');});
test('late mismatch body from A cannot expire B',async()=>{const id=new Identity();id.accept('A');const a=id.capture(),s=stream();const response=new Response(s.response.body,{status:409});const pending=readProtected(response,()=>id.current(a),()=>assert.fail('must not expire B'));s.send('{"error":');await Promise.resolve();id.accept('B');s.send('"session_expired"}');s.close();await assert.rejects(pending,StaleResponse);});
test('current SSE expiry terminates before a following private frame in the same chunk',async()=>{const id=new Identity();id.accept('A');const a=id.capture(),s=stream();const seen:unknown[]=[];let expired=0;const pending=readProtected(s.response,()=>id.current(a),()=>{expired++;id.accept(null,true);},e=>seen.push(e));s.send(frame({type:'session_expired'})+frame({type:'answer',reply:'private'}));await assert.rejects(pending,StaleResponse);assert.equal(expired,1);assert.deepEqual(seen,[]);assert.equal(s.cancelled(),true);});
test('old SSE expiry does not expire B and cancels its reader',async()=>{const id=new Identity();id.accept('A');const a=id.capture(),s=stream();const pending=readProtected(s.response,()=>id.current(a),()=>assert.fail('must not expire B'),()=>assert.fail('must not deliver'));id.accept('B');s.send(frame({type:'session_expired'}));await assert.rejects(pending,StaleResponse);assert.equal(s.cancelled(),true);assert.equal(id.owner,'B');});
test('partial frames and malformed JSON preserve normal messages; callback error escapes',async()=>{const s=stream(),seen:string[]=[];const pending=readProtected(s.response,()=>true,()=>{},e=>{seen.push(e.type);if(e.type==='error')throw new Error('visible failure');});s.send('data: {bad}\n\ndata: {"type":"sta');s.send('tus"}\n\n'+frame({type:'error'})+frame({type:'answer'}));await assert.rejects(pending,/visible failure/);assert.deepEqual(seen,['status','error']);assert.equal(s.cancelled(),true);});
test('legitimate current JSON and write headers stay usable',async()=>{const id=new Identity();id.accept('A');const a=id.capture();assert.deepEqual(await readProtected(new Response('{"ok":true}'),()=>id.current(a),()=>{}),{ok:true});assert.equal(protectedHeaders('A','token','PATCH')['X-GSTPilot-CSRF'],'token');});
