"use client";
// Owner identity and response fences are shared with the conversation workspace.
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, Pencil, Trash2 } from 'lucide-react';
import { useRequests } from '@/components/AccountShell';
type Fact = { id: string; fact: string; value: string; kind: 'behavioral' | 'default'; as_of: string; last_confirmed: string | null; effective_confidence: number; stale: boolean };
type Memory = { profile?: { email?: string; sells?: string; state?: string }; facts: Fact[] };
const LABELS: Record<string, string> = { sells: 'What you sell', state: 'State', platforms: 'Where you sell', turnover_band: 'Approximate turnover', filing_frequency: 'Filing frequency' };
function label(value: string) { return LABELS[value] ?? value.replace(/^observation:/, 'Note: ').replace(/^default:/, 'Shortcut: ').replace(/[_.-]/g, ' '); }
export default function MemoryPage() {
  const requests = useRequests(); const [facts, setFacts] = useState<Fact[]>([]); const [profile, setProfile] = useState({ sells: '', state: '' }); const [loaded, setLoaded] = useState(false); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  async function load() { const result = await requests.request<Memory>('/api/memory'); if (result) { setFacts(result.facts ?? []); setProfile({ sells: result.profile?.sells ?? '', state: result.profile?.state ?? '' }); setLoaded(true); } }
  useEffect(() => { const ticket = requests.capture(); void load().catch(() => { if (requests.current(ticket)) { setLoaded(true); setError('Your saved details could not be loaded. Reload to retry.'); } }); }, []);
  async function mutate(method: string, url: string, body: unknown, success: string) { const ticket = requests.capture(); setBusy(true); setError(''); setNotice(''); try { await requests.request(url, method, body); if (!requests.current(ticket)) return; await load(); if (requests.current(ticket)) { setEditing(null); setNotice(success); } } catch (e) { if (requests.current(ticket)) setError(e instanceof Error ? e.message : 'The change was not saved. Please retry.'); } finally { if (requests.current(ticket)) setBusy(false); } }
  return <main className="memory-page"><Link href="/" className="row small text-link"><ArrowLeft size={15} />Back to conversations</Link><div><h1>What GSTPilot remembers</h1><p className="muted mt-3">Review what was learned, correct a detail, or remove it. Older unconfirmed facts become less trusted.</p></div>
    {error && <div className="alert danger" role="alert">{error}</div>}{notice && <p className="alert" role="status">{notice}</p>}
    {!loaded ? <p role="status" className="muted">Loading your saved details…</p> : <>
      <section><h2>Business profile</h2><form className="memory-card stack" onSubmit={e => { e.preventDefault(); void mutate('PATCH', '/api/user', profile, 'Business profile saved.'); }}><label>What do you sell?<input className="input" maxLength={200} required value={profile.sells} onChange={e => setProfile(p => ({ ...p, sells: e.target.value }))} /></label><label>State<input className="input" maxLength={80} required value={profile.state} onChange={e => setProfile(p => ({ ...p, state: e.target.value }))} /></label><div><button className="btn primary" disabled={busy}>{busy ? 'Saving…' : 'Save profile'}</button></div></form></section>
      {[{ title: 'Learned from conversations', kind: 'behavioral', empty: 'No learned facts yet. They will appear here as you chat.' }, { title: 'Confirmed shortcuts', kind: 'default', empty: 'Shortcuts appear here when you confirm an assumption.' }].map(group => <section key={group.kind}><h2>{group.title}</h2>{facts.filter(f => f.kind === group.kind).length === 0 && <p className="muted small">{group.empty}</p>}{facts.filter(f => f.kind === group.kind).map(f => <article className="memory-card memory-fact" key={f.id}><div><p className="muted small">{label(f.fact)}</p>{editing === f.id ? <form className="stack" onSubmit={e => { e.preventDefault(); void mutate('PATCH', '/api/memory', { id: f.id, value: draft.trim() }, 'Saved fact updated.'); }}><label className="sr-only" htmlFor={`fact-${f.id}`}>Correct {label(f.fact)}</label><input id={`fact-${f.id}`} className="input" autoFocus maxLength={200} value={draft} onChange={e => setDraft(e.target.value)} /><div className="row"><button className="btn" disabled={busy || !draft.trim()}>Save</button><button className="btn" type="button" onClick={() => setEditing(null)}>Cancel</button></div></form> : <p>{f.value}</p>}<p className="small muted">As of {f.as_of.slice(0, 10)} · {f.last_confirmed ? `confirmed ${f.last_confirmed.slice(0, 10)}` : 'unconfirmed'}{f.stale ? ' · needs confirmation' : ''}</p><div className="fact-actions"><button className="row" disabled={busy} onClick={() => { setEditing(f.id); setDraft(f.value); }}><Pencil size={13} />Edit</button><button className="row" disabled={busy} onClick={() => void mutate('DELETE', '/api/memory', { id: f.id }, 'Saved fact removed.')}><Trash2 size={13} />Delete</button></div></div><div className="memory-meter"><progress value={Math.max(0, Math.min(1, f.effective_confidence))} max={1} aria-label={`Confidence for ${label(f.fact)}`} /><p>{Math.round(f.effective_confidence * 100)}% confidence</p></div></article>)}</section>)}
      <p className="small muted">Remembered details provide context. Calculation inputs still need your confirmation.</p>
    </>}
  </main>;
}
