import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {query,closeDatabase} from '../lib/server/db';
import {withExecution,type Execution} from '../lib/server/execution';
import {createThread,getThread,appendMessage,listMessages,remember,getFacts,setFeedback,deleteFact} from '../lib/repositories/business';
import {reserve,markDispatched,settle,uncertain} from '../lib/server/usage';
import {csrfToken,validCsrf} from '../lib/server/security';
import {analyzeFiling,EXAMPLE_FACTS} from '../lib/server/filing';
import {compactIfNeeded} from '../lib/memory/compact';
const checks:string[]=[];
const test=async(name:string,fn:()=>unknown|Promise<unknown>)=>{await fn();checks.push(name);};
async function actor(){const ownerId=randomUUID(),sessionId=randomUUID();await query('insert into gstpilot_users(id,email,password_hash) values($1,$2,$3)',[ownerId,ownerId+'@test.invalid','fixture-not-a-login']);await query('insert into gstpilot_user_profile(user_id,email) values($1,$2)',[ownerId,ownerId+'@test.invalid']);await query("insert into gstpilot_sessions(id,owner_id,expires_at) values($1,$2,now()+interval '1 hour')",[sessionId,ownerId]);return {ownerId,sessionId,requestId:randomUUID(),mode:'live' as const,purpose:'chat' as const,deadlineMs:Date.now()+120000};}
async function main(){
 const a=await actor(),b=await actor();const ta=await createThread(a.ownerId,'A synthetic thread','chat'),tb=await createThread(b.ownerId,'B synthetic thread','chat');
 await test('no actor fails closed',async()=>{await assert.rejects(()=>appendMessage(ta.id,'user','anonymous'));});
 await test('A and B concurrent completions stay owned',async()=>{await Promise.all([withExecution(a,async()=>{await new Promise(r=>setTimeout(r,25));await appendMessage(ta.id,'assistant','A result');}),withExecution(b,async()=>{await appendMessage(tb.id,'assistant','B result');})]);assert.equal((await listMessages(a.ownerId,ta.id))[0].content,'A result');assert.equal((await listMessages(b.ownerId,tb.id))[0].content,'B result');});
 await test('foreign thread read and append denied',async()=>{await assert.rejects(()=>getThread(b.ownerId,ta.id));await assert.rejects(()=>withExecution(b,()=>appendMessage(ta.id,'user','cross owner')));});
 await test('foreign feedback denied',async()=>{const m=(await listMessages(a.ownerId,ta.id))[0];await assert.rejects(()=>setFeedback(b.ownerId,m.id,'up',null));});
 await test('memory provenance cannot refer to another owner thread',async()=>{await assert.rejects(()=>withExecution(a,()=>remember(a.ownerId,'platforms','Synthetic',tb.id)));});
 await test('memory edits and deletion are owner-scoped',async()=>{await withExecution(a,()=>remember(a.ownerId,'platforms','Synthetic',ta.id));const f=(await getFacts(a.ownerId))[0];await assert.rejects(()=>deleteFact(b.ownerId,f.id));assert.equal((await getFacts(b.ownerId)).length,0);});
 await test('database composite FK rejects owner reparenting',async()=>{await assert.rejects(()=>query("insert into gstpilot_messages(id,thread_id,owner_id,role,content) values($1,$2,$3,'user','reparent')",[randomUUID(),ta.id,b.ownerId]));});
 await test('shared legal corpus and privileged refresh denied',async()=>{await assert.rejects(()=>query("delete from gstpilot_legal_chunks where false"));await assert.rejects(()=>query('truncate gstpilot_messages'));await assert.rejects(()=>query('select gstpilot_refresh_lexeme_stats()'));await assert.rejects(()=>query('create table should_be_denied(id integer)'));assert.deepEqual((await query("select * from gstpilot_keyword_search('filing',8)")).rows,[]);});
 await test('CSRF valid across same-session reads and Unicode forged signatures rejected',async()=>{const token=csrfToken(null,'session:'+a.sessionId);assert(validCsrf(token,'session:'+a.sessionId));assert.equal(csrfToken(token,'session:'+a.sessionId),token);assert(!validCsrf(token,'session:'+b.sessionId));assert(!validCsrf(token.split('.')[0]+'.'+'é'.repeat(43),'session:'+a.sessionId));const anon=csrfToken(null,'anonymous-signup');assert(validCsrf(anon,'anonymous-signup'));});
 await test('prepared historical formula has zero usage and no extraction',async()=>{const before=(await query('select count(*) n from gstpilot_usage')).rows[0].n;const r=await withExecution({...a,mode:'prepared',purpose:'filing'},()=>analyzeFiling(EXAMPLE_FACTS));assert.equal(r.calculation?.payable,300);assert.equal(r.calculation?.days_late,6);assert.equal(r.prepared,true);assert.equal(r.citations.length,2);assert.equal((await query('select count(*) n from gstpilot_usage')).rows[0].n,before);});
 await test('prepared T3 never calculates',async()=>{const r=await withExecution({...a,mode:'prepared',purpose:'filing'},()=>analyzeFiling(EXAMPLE_FACTS+' A DRC-01 notice is pending.'));assert.equal(r.tier,'T3');assert.equal(r.calculation,null);});
 await test('long chat compaction preserves owner boundary and earlier summary',async()=>{const t=await createThread(a.ownerId,'long synthetic chat','chat');await withExecution(a,async()=>{for(let i=0;i<26;i++)await appendMessage(t.id,i%2?'assistant':'user','Synthetic conversation fact '+i);await compactIfNeeded(t.id);});const own=await getThread(a.ownerId,t.id);assert.equal(Number(own.summary_upto),6);assert(own.summary.length>0);await assert.rejects(()=>withExecution(b,()=>compactIfNeeded(t.id)));assert.equal((await getThread(a.ownerId,t.id)).summary,own.summary);});
 // No provider transport is called: only durable state transitions are exercised below.
 process.env.GSTPILOT_MOCK_MODE='0';
 const quote={provider:'openai',model:'gpt-4o-mini',inputBytes:500,maxOutputTokens:300,inputPrice:0.15,outputPrice:0.6,cachedPrice:0.075};
 await test('known usage remains complete after semantic failure',async()=>{await withExecution(a,async()=>{const id=await reserve(quote);await markDispatched(id);await settle(id,{inputTokens:100,outputTokens:10,cachedInputTokens:20,providerModel:'gpt-4o-mini-2024-07-18'});await uncertain(id);const row=(await query('select * from gstpilot_usage where id=$1',[id])).rows[0];assert.equal(row.status,'complete');assert.equal(Number(row.actual_usd),0.0000195);});});
 await test('settlement cannot touch another owner row',async()=>{let id='';await withExecution(a,async()=>{id=await reserve(quote);await markDispatched(id);});await withExecution(b,()=>settle(id,{inputTokens:1,outputTokens:1}));assert.equal((await query('select status from gstpilot_usage where id=$1',[id])).rows[0].status,'dispatched');await withExecution(a,()=>uncertain(id));});
 await test('revocation between reserve and dispatch restores undispatched capacity',async()=>{const fresh=await actor();await withExecution(fresh,async()=>{const id=await reserve(quote);await query('update gstpilot_sessions set revoked_at=now() where id=$1',[fresh.sessionId]);await assert.rejects(()=>markDispatched(id));assert.equal((await query('select status from gstpilot_usage where id=$1',[id])).rows[0].status,'released');});});
 await test('filing request permits at most one provider reservation',async()=>{await withExecution({...b,purpose:'filing'},async()=>{const id=await reserve(quote);await markDispatched(id);await settle(id,{inputTokens:20,outputTokens:5});await assert.rejects(()=>reserve(quote));});});
 await test('expired deadline rejects without ledger mutation',async()=>{const before=(await query('select count(*) n from gstpilot_usage')).rows[0].n;await assert.rejects(()=>withExecution({...a,deadlineMs:Date.now()-1},()=>reserve(quote)));assert.equal((await query('select count(*) n from gstpilot_usage')).rows[0].n,before);});
 await test('fractional cached usage stays conservative',async()=>{await withExecution({...a,requestId:randomUUID()},async()=>{const id=await reserve(quote);await markDispatched(id);await settle(id,{inputTokens:10,outputTokens:5,cachedInputTokens:0.2});assert.equal((await query('select status from gstpilot_usage where id=$1',[id])).rows[0].status,'uncertain');});});
 process.env.GSTPILOT_MOCK_MODE='1';
 console.log(JSON.stringify({status:'passed',checks,count:checks.length,real_provider_calls:0,ownerA:a.ownerId,ownerB:b.ownerId}));
}
main().catch(e=>{console.log(JSON.stringify({status:'failed',checks,category:e?.name,message:String(e?.message).slice(0,200)}));process.exitCode=1;}).finally(closeDatabase);
